### PR TITLE
README fixes

### PR DESCRIPTION
**Pull request by szarnyasg**
Some simple fixes in the README

### CODE REVIEW

**Comment by szarnyasg** [comment]
I'd like to clarify the network settings for Postfix in the README. IP #441 got rid of hardcoded IPs which led to some challenges.

1. How to set `mynetworks` in Postfix's `main.cf`? I added this:

```diff
+
+# example: add the containers with IPs 172.19.199.x to mynetworks
+mynetworks = 127.0.0.0/8 172.19.199.0/24 [::ffff:127.0.0.0]/104 [::1]/128
```

   This works but it's important to note that since #441 the subnet can change if the network is recreated. So, for Postfix, it's probably best to stick using fixed IPs.

2. The default `smtp_host` in the mailman-core container binds to the gateway. I think `smtp.example.com` is misleading as we want the Postfix on the host machine to relay the messages to the SMTP server.
 
   I'd change this as follows:

```diff
-# Postfix server's hostname or IP from mailman-core
-smtp_host: smtp.example.com
+# Postfix server's hostname or IP address
+smtp_host: <gateway's IP address>
```

WDYT?

**Comment by szarnyasg** [comment]
Fixed the default value of `MM_HOSTNAME` (as it was changed in PR #454).

Considering that this is now not a hostname but an IP address, I'd also propose changing `MM_HOSTNAME` to `MAILMAN_HOST`.

**Comment by maxking** [comment]
Thanks very much for you contribution and carefully fixing the issues in the documentation! This is really awesome!

**Comment by szarnyasg** [comment]
@maxking happy to help.

One thing: the PR did not contain the changes mentioned in https://github.com/maxking/docker-mailman/pull/464#issuecomment-844187870 as I was unsure about whether you agree with them. I'm opening a new PR with those.

**Pull request merged**
