### PR TITLE
Support base_path for mailman-web

### PR DESCRIPTION
**Pull request by sehaas**
add BASE_PATH environment variable for configuring a base path
for static and dynamic requests

### CODE REVIEW

**Comment by maxking** [comment]
You don't need app level changes to support deploying application at a sub-path for this to work, although, you do need to modify the uwsgi configuration which can be done by creating your own and using that one.x

I deployed a sample instance at https://mailman.araj.me/mm3/mailman3/lists/, with `/mm3` prefix to the path.

I created this in uwsgi.ini to let it serve at a sub-path.
```
mount = /mm3=mailman_web.wsgi:application
manage-script-name = true
```

But, for the container images, you can update this file https://github.com/maxking/docker-mailman/blob/main/web/mailman-web/uwsgi.ini as:
```
# Use the wsgi file provided with the django project.
# wsgi-file = wsgi.py
mount = /mailman=wsgi.py
manage-script-name = true
```

For the Nginx configuration, it looks like this:
```
       location /mm3/static {
            alias /opt/mailman3/web/static;
            autoindex off;
        }

        location /static {
            alias /opt/mailman3/web/static;
            autoindex off;
        }

        location /mm3 {
                uwsgi_pass localhost:8080;
                uwsgi_param SCRIPT_NAME /mm3;
                include uwsgi_params;
                uwsgi_read_timeout 300;
         }
```

(Note that I am slightly confused about the URL for the static, I think it should alias `/mm3/static` but i added both and it works for now. Needs some more investigation).

**Comment by sehaas** [comment]
Thanks for the feedback.
I took a look at your instance - the static files are still loaded from `/static` and not the sub path, so maybe the change in `settings.py` is needed after all.

Overwriting the `uwsig.ini` only works if I'm building the image myself, right? Or is there a way to parameterize the file with environment variables?

**Comment by maxking** [comment]
I still need to experiment with https://docs.djangoproject.com/en/3.2/ref/settings/#force-script-name (FORCE_SCRIPT_NAME) in django’s settings to see if that changes anything.

Ideally, the SCRIPT_NAME should be passed in to Django and that should be pre-pended to the STATIC_PATH value. The second thing to try would be to override STATIC_URL in settings.py to `/mm3/static`. https://docs.djangoproject.com/en/3.2/ref/settings/#std:setting-STATIC_URL

If you check the dockerfile, the uwsgi.ini path is just a `CMD` option. You can easily override that CMD to a path of your own choosing with the new uwsgi.ini configuration.

**Comment by maxking** [comment]
Ok, so setting the `STATIC_URL = '/mm3/static/'` worked for me, I removed the `/static/` url pattern in my Nginx config.

Check it out at mailman.araj.me.

**Comment by maxking** [comment]
Thanks for this, but I am closing this one.

**Pull request closed without merging**
