### PR TITLE
fix mailman.cfg issue

### PR DESCRIPTION
**Pull request by aiomaster**
We have to append ">>" to /etc/mailman.cfg and not to overwrite previously written content with ">".
Problem was that the database config made in setup_database was overriden.

### CODE REVIEW

**Comment by maxking** [comment]
Thank you very much for this!

**Comment by maxking** [comment]
It looks like we have problems compiling cryptography in alpine, perhaps we can find libffi somewhere (or just python3-cryptography somewhere compiled in alpine packages?

**Comment by aiomaster** [comment]
Why don't you just add [libffi-dev](https://pkgs.alpinelinux.org/packages?name=libffi-dev&branch=v3.6) to the apk add?

**Comment by aiomaster** [comment]
Hey @maxking,
I think I have fixed your CI stuff.
There are some small issues while build for example:
"hyperkitty 1.1.4 has requirement Django<1.11, but you'll have django 1.11 which is incompatible."
or sometimes I've seen something like:
"Failed building wheel for uwsgi"
but the whole thing seems to work.

**Comment by maxking** [comment]
Thanks a lot @aiomaster for fixing all the issues. 

I will go ahead and merge this.

**Comment by maxking** [comment]
Turns out, master fails to build becuase PyYaml doesn't build on Python 3.7 (for some reason that I haven't explored yet: https://github.com/yaml/pyyaml/issues/126).

**Pull request merged**
