### PR TITLE
Build optimizations

### PR DESCRIPTION
**Pull request by am97**
[wait-for-it](https://github.com/vishnubob/wait-for-it) is a widely used script for checking if a service is responding on a given port. 

This PR reduces the uncompressed size of maxking/mailman-web from 248MB to 229MB, and simplifies the code a bit.

I tested it with Postgres and MariaDB

### CODE REVIEW

**Comment by am97** [comment]
Hello @maxking , I rebased my PR on `main`, it is ready to be merged. Let me know if you're not interested in optimizations ;)

**Comment by maxking** [comment]
Hey @am97, thanks for taking time to work on this :-)

I would like to avoid depending on yet-another script for code that is already there. More dependencies tend to bite in the future and existing code to check for server is simple enough that I don't mind maintaining it.

The optimizations are nice, if you can remove the changes for wait-for-it, we can go ahead with merging this.

**Comment by am97** [comment]
Ok no problem, I left just the optimizations so I changed the title of the PR. 

Are you still open to the following in a separate PR ?

```sh
	# TODO: Use python3's psycopg2 module to do this in python3 instead of
	# installing postgres-client in the image.
```

**Comment by maxking** [comment]
Yeah, we can do that. Although, i've also been thinking if we can just use composes' new startup order feature instead of doing it manually in the entrypoint script (although, maybe outside of compose, there is some value in having the checks in entrypoint script)

https://docs.docker.com/compose/startup-order/

**Comment by am97** [comment]
> Yeah, we can do that. Although, i've also been thinking if we can just use composes' new startup order feature instead of doing it manually in the entrypoint script (although, maybe outside of compose, there is some value in having the checks in entrypoint script)
> 
> https://docs.docker.com/compose/startup-order/

That sounds better at first sigh, although it has some drawbacks:

* The Compose v2 plugin would be required
* It won't work in Swarm mode, which is what I'm using to deploy this image (there doesn't seem to be a lot of people using Swarm mode however, and I can adapt)

**Pull request merged**
