### PR TITLE
Add SMTP_USER, SMTP_PASSWORD from environment vars.

### PR DESCRIPTION
**Pull request by joergmschulz**
add smtp user, password from environment to mailman.cfg

### CODE REVIEW

**Comment by joergmschulz** [comment]
this allows the smtp credentials to be entered in docker-compose.yml

**Comment by maxking** [comment]
Can you also add the new variables to https://github.com/maxking/docker-mailman/tree/main/core/README.md please?

Otherwise, it LGTM!

**Comment by maxking** [comment]
Can you please add the doc to this PR isntead of #597? Which also seem to have some extraneous.

**Comment by maxking** [comment]
Can you also remove the last comming with the compose file? I don't see it having any traefik server actually or any documentation to help use it :-) It might best proposed as a separate Issue and PR.

**Comment by joergmschulz** [comment]
will create new PR

**Pull request closed without merging**
