### PR TITLE
Remove defaulted SECRET_KEY

### LINKED ISSUE #99: Vulnerability: SECRET_KEY is default
https://github.com/maxking/docker-mailman/blob/4373111/web/mailman-web/settings.py#L35

Proposed solution: remove this line and force any vulnerable users updated to set it.

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Close #99

This will prevent any vulnerable configuration from starting, but I consider it a correct approach.

### CODE REVIEW

**Comment by maxking** [comment]
Can you also add a check in the entrypoint script to exit before starting Django if SECRET_KEY is not defined?

**Comment by ishitatsuyuki** [comment]
I don't think that's necessary, since I have deliberately coded to trigger the warning coded in Django itself.

Also, I think the test will fail. What do you think is optimal?

**Comment by maxking** [comment]
The reason I like to do checks in the entrypoint script is because I can easily control the wording of the error message telling the user to define an environment variable.

A large python traceback with less-user-friendly message would make some people think if the application is broken or something is needed that they need to define.

Tests just generate a sample docker-compose.yaml file from a simple bash script, if you edit the bash script you can add a SECRET_KEY environment variable.

**Comment by maxking** [comment]
https://github.com/maxking/docker-mailman/blob/master/tests/generate_tests.sh

This is the script that generates testing configuration.

**Comment by ishitatsuyuki** [comment]
CI passed, merge please.

**Comment by maxking** [comment]
Thanks for your contribution!

**Pull request merged**
