### PR TITLE
Add support for CACHES. 

### PR DESCRIPTION
**Pull request by maxking**

### CODE REVIEW

**Comment by danil-smirnov** [comment]
Should we also move to multi-process mode for uwsgi @maxking ?

https://github.com/maxking/docker-mailman/blob/main/web/mailman-web/uwsgi.ini#L17

**Comment by maxking** [comment]
@danil-smirnov yeah, I think we can safely bump the number of processes now.

**Comment by danil-smirnov** [comment]
@maxking I'm not sure what processes/threads configuration is reasonable actually... I didn't hit any issue with the 1/2 setup. Do we really need to use multiple processes here?...

**Comment by maxking** [comment]
It really depends on how much traffic do you get on your webserver. I *think* 2 workers with 2 threads each should suffice for most people. It might be good to have 2 workers to take advantage of 2 Cores and then spin off 2 threads each (threads are much cheaper resources wise, compared to workers) so we have some headroom for high traffic times.

**Comment by danil-smirnov** [comment]
Then let's apply it @maxking :)
https://github.com/maxking/docker-mailman/pull/470

**Comment by danil-smirnov** [comment]
I wonder if Postorius image should have the same configuration @maxking ?
The current [four processes](https://github.com/maxking/docker-mailman/blob/main/postorius/mailman-web/uwsgi.ini#L14) look a bit overkill to me...

**Comment by maxking** [comment]
We can probably do the same with Postorius, its not that much of an overhead.

**Comment by danil-smirnov** [comment]
@maxking Then this is it: https://github.com/maxking/docker-mailman/pull/472

**Pull request merged**
