### PR TITLE
Fix uWSGI cron configuration

### LINKED ISSUE #87: Cron is running wrongly
From the logs, at least "monthly" is running every minute. You're writing cron syntax wrongly.

TLDR: Fill out all values (instead of only one), or they will be replaced with wildcard.

I'm not sure if this is the reason that my archive isn't being generated?

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
The missing daily routines are also added.

Close #87

P.S.: actually there's [quarter_hourly](https://github.com/django-extensions/django-extensions/blob/d195301ebbd002e98989cad05657f552cc54f96c/django_extensions/management/commands/runjobs.py#L61), but I choose to ignore it as postorious doesn't use it.

### CODE REVIEW

**Comment by maxking** [comment]
Turns out, [Hyperkitty](https://gitlab.com/mailman/hyperkitty/blob/master/example_project/crontab) (Postorius doesn't use the cron, Hyperkitty which is the archiver does) does have a quarter_hourly job (Which I missed in the first place).

While you are at it, would you mind adding quarter_hourly too?

Thanks a lot for finding this and fixing!

**Comment by ishitatsuyuki** [comment]
What you mentioned doesn't seem to be actually doing something (it's purely a sample configuration), but I have added it anyway.

**Comment by maxking** [comment]
That does turn out to be true, maybe that is the reason I skipped it the last time. Nevermind, it doesn't harm to put it incase HK devs decide to add something later.

Thanks again. Will merge when CI finishes.

**Comment by ishitatsuyuki** [comment]
Merge?

**Pull request merged**
